### ISSUE TITLE
running test

### ISSUE THREAD

**Issue by sainsgeo** [klaundal/pyAMPS#11]
I tried to run the following script in Python3.7,

from pyamps import AMPS
m = AMPS(350,-4,-3, 20,80)
m.plot_currents()

but an error raised as follows:

Traceback (most recent call last):
  File "/home/bio/Downloads/pyAMPS-master/pyAMPS-master/pyamptests1.py", line 8, in <module>
    m.plot_currents()
  File "/home/bio/Downloads/pyAMPS-master/pyAMPS-master/pyamps/amps.py", line 1310, in plot_currents
    pax_n.featherplot(mlatv, mltv, nn , en, SCALE = vector_scale, markersize = 10, unit = 'mA/m', linewidth = '.5', color = 'gray', markercolor = 'grey')
  File "/home/bio/Downloads/pyAMPS-master/pyAMPS-master/pyamps/plot_utils.py", line 227, in featherplot
    self.ax.plot([0.9, 1], [0.95, 0.95], color = colors, linestyle = '-', linewidth = 2)
NameError: name 'colors' is not defined

Then, i tried to define colors in plot_utils.py but the errors still raised.

**Comment by klaundal** [comment]
Ooops, I missed that, sorry! And thank you for making me aware of it! I have fixed it now, but the plotting still doesn't work because of some other issue. I'll fix that too, hopefully quite soon

**Comment by klaundal** [comment]
The plotting should work again now. You'll need to upgrade to the newest version (1.5.2): `pip install pyamps -U`

**Comment by sainsgeo** [comment]
thanks you, it is working now
